version: '2'

services:
    mysql-development:
        image: mysql:5.7.27
        environment:
          MYSQL_ROOT_PASSWORD: helloworld
          MYSQL_DATABASE: testapp
        ports:
          - "3306:3306"
        volumes:
          - my-db:/var/lib/mysql
          - ./my.cnf:/etc/mysql/my.cnf

volumes:
  my-db:
